name: DailyTests2

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run crawl of test website
        run: |
          docker run \
            -v $(pwd):/output \
            ghcr.io/openzim/zimit \
            zimit \
            --seeds https://shahvani.com/ \
            --name shahvani-website \
            --output /output
