name: DailyTests2

on:
  workflow_dispatch:


jobs:
  run:
    runs-on: [ubuntu-24.04]

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: run crawl of test website
        run: docker run -v ghcr.io/openzim/zimit local-zimit zimit --seeds https://shahvani.com/ --name shahvani-website --zim-file shahvani.zim
